### ISSUE TITLE
Enable Search within Alias Descriptions

### ISSUE THREAD

**Issue by Bazixv13** [anonaddy/addy-android#2]
Is your feature request related to a problem? Please describe.
When creating aliases through tools like Bitwarden, descriptions are autogenerated (e.g., “Website: https://example.com. Generated by Bitwarden”). Currently, there’s no way to search within descriptions, making it hard to locate specific aliases quickly. So searching "example" would give you nothing.

Describe the solution you’d like
Add a search feature that includes alias descriptions, allowing users to find aliases by words within the description.

Describe alternatives you’ve considered
Manually going to any email from x alias, clicking "deactivate this alias," and opening it in the app. This search feature would streamline the process, though it’s a minor improvement.

Additional context
low-priority request

**Comment by willbrowningme** [comment]
Searching aliases by their description is already possible and works perfectly in the app.

I just created an alias and gave it that exact description:

`Website: https://example.com/. Generated by Bitwarden`

Then searched "example" in the app and it found the alias as expected.
