### ISSUE TITLE
Alias defaults

### ISSUE THREAD

**Issue by hegehog8761** [anonaddy/addy-android#7]
**Is your feature request related to a problem? Please describe.**
The request is not an issue however I think that it would be very nice to be able to have a way of setting a default for the new alias menu

**Describe the solution you'd like**
Somewhere in the app settings there would be a way to change the default alias domain, format and recipients

**Describe alternatives you've considered**
A system of automatically selecting the previous options of said values could be implemented though a set default would likely be better

**Additional context**
This is the menu and values which I am referring to
![20241209_160158.jpg](https://github.com/user-attachments/assets/814f0ef1-be3b-4c15-8e05-38f818fa8ff3)

**Comment by willbrowningme** [comment]
You can set the default alias domain and format in your account settings here - [https://app.addy.io/settings](https://app.addy.io/settings)

This should be reflected in the mobile app and browser extensions.

**Comment by hegehog8761** [comment]
Thank you for this information and while format and domain can be changed, I can't appear to find a setting to change the forward to address default

**Comment by hegehog8761** [comment]
I have already got my email address set as my default in the website but this is not reflected in the app.

**Comment by willbrowningme** [comment]
If it is already set as default then you can simply leave the "Select recipient for this alias" option blank when creating an alias and it will automatically forward to your account's default one.

**Comment by hegehog8761** [comment]
Sorry for the hassle, I simply assumed with it not being ticked in the UI, my sincerest appollogies and thank you very much for both the great help and amazing app.
